version: '3'
services:
  web_app:
    container_name: ponyo-plants
    build: .
    ports:
      - '5001:5001'
    environment:
      - DATABASE_CONNECTION_STRING=mongodb+srv://ykim021227:gKP6MGYC0lAI96bb@plant.zm0eyo8.mongodb.net/?retryWrites=true&w=majority
      - FLASK_SECRET_KEY
      - API_KEY
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
