version: '3'
services:
  web_app:
    container_name: ponyo-plants
    # restart: always
    build: .
    ports:
      - '5001:5001'
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'