name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest 
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t rafinator123/ponyo-plants .
        docker tag rafinator123/ponyo-plants:latest
        docker push rafinator123/ponyo-plants:latest

    - name: Deploy to Digital Ocean
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 104.131.66.30 >> ~/.ssh/known_hosts
        echo "${{ secrets.DROPLET_PASSWORD }}" | sshpass ssh -o StrictHostKeyChecking=no root@104.131.66.30 "
        cd 5-final-project-ponyo &&
        docker-compose down &&
        git pull origin main &&
        docker-compose build --no-cache &&
        docker-compose up -d" || true
